models:

  type1:
    width: 250
    height: 50
    net_chanels: 1
    fill_color: 255
    letters: '$$.0123456789abcdefghijklmnopqrstuvwxy'
    ctc_input_length: 61
    max_label_length: 7
    model_path: './models/type1.hdf5'

  type3:
    width: 200
    height: 60
    net_chanels: 3
    fill_color: 255
    letters: " #$$'+,-0123456789abcdefghijklmnopqrstuvwxyz"
    ctc_input_length: 48
    max_label_length: 8
    model_path: './models/type3.hdf5'

  type4:
    width: 190
    height: 50
    net_chanels: 3
    fill_color: 255
    letters: '123456789abcdefghijklmnpqrstuvwxyz'
    ctc_input_length: 12
    max_label_length: 7
    model_path: './models/type4.hdf5'
  
  type5:
    width: 160
    height: 90
    net_chanels: 3
    fill_color: 255
    letters: '23456789abcdegikpqsvxyz'
    ctc_input_length: 16
    max_label_length: 7
    model_path: './models/type5.hdf5'

  type6:
    width: 95
    height: 40
    net_chanels: 3
    fill_color: 255
    letters: " !'+,.0123456789;[abcdefghijklmnopqrstuvwxyzóабвгдежзийклмнопрстуфхцчшщъыьэюяєі"
    ctc_input_length: 16
    max_label_length: 7
    model_path: './models/type6.hdf5'

  type7:
    width: 100
    height: 60
    net_chanels: 3
    fill_color: 255
    letters: '23456789abcdegikpqsvxyz'
    ctc_input_length: 24
    max_label_length: 7
    model_path: './models/type7.hdf5'

  type8:
    width: 100
    height: 60
    net_chanels: 3
    fill_color: 255
    letters: ' 0123456789^abcdefghijklmnopqrstuvwxyzавл'
    ctc_input_length: 24
    max_label_length: 9
    model_path: './models/type8.hdf5'
